Fix issues when downloading FSO builds from GitHub
scp-fs2open/fsoinstaller pull request #5
Opened 2017-09-02 09:33 UTC by asarium

There were multiple issues when trying to download build archives from GitHub:
  1. The URL validator only checked if the HTTP protocol was used but GitHub uses HTTPS.
  2. GitHub does not allow HEAD requests for their resources. I added a fallback which uses GET if the HEAD request fails.

2017-09-02 22:22 UTC, Goober5000 requested changes
Looks good, for the most part (except for change in brace style, but I can ignore that).  Just two small changes requested.

2017-09-02 22:22 UTC, Goober5000 commented on src/com/fsoinstaller/internet/Connector.java
> +			logger.debug("Host failed to retreive content length with HEAD, retrying with GET...");
Could you make the logger log the exception as well as the message?

2017-09-02 22:22 UTC, Goober5000 commented on src/com/fsoinstaller/internet/Connector.java
> +			logger.debug("Host failed to retreive last modifies with HEAD, retrying with GET...");
Here too.

2017-09-03 09:00 UTC, asarium commented
I changed the log statements to `info` calls and added the exception to the statement.

2017-09-03 09:07 UTC, asarium commented
I didn't notice that I used the wrong brace style. I think I fixed that now,

2017-09-06 15:57 UTC, Goober5000 approved these changes

2017-09-06 15:57 UTC, Goober5000 commented
:+1:

2017-09-06 15:57 UTC, merged